-- Migration 005: Scheduled Reports System
-- SPEC-RPT-001: Reporting and Analytics System
-- Created: 2025-01-04

-- Table: scheduled_reports
-- Stores report schedule configurations for automated report generation
CREATE TABLE IF NOT EXISTS scheduled_reports (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT 'Human-readable name for the scheduled report',
    description TEXT NULL COMMENT 'Detailed description of the report purpose',
    created_by BIGINT NOT NULL COMMENT 'User ID who created the schedule',
    report_config JSON NOT NULL COMMENT 'Full report configuration (filters, grouping, format)',
    schedule_type ENUM('once', 'daily', 'weekly', 'monthly', 'quarterly') NOT NULL COMMENT 'Type of schedule',
    schedule_config JSON NOT NULL COMMENT 'Schedule-specific configuration (time, day, timezone)',
    is_active BOOLEAN DEFAULT TRUE COMMENT 'Whether the schedule is currently active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When the schedule was created',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_schedule_type (schedule_type),
    INDEX idx_is_active (is_active),
    INDEX idx_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Scheduled report configurations';

-- Table: report_generation_log
-- Tracks all report generation history including scheduled and manual reports
CREATE TABLE IF NOT EXISTS report_generation_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    scheduled_report_id BIGINT NULL COMMENT 'Reference to scheduled report if generated by schedule',
    report_name VARCHAR(255) NOT NULL COMMENT 'Name of the generated report',
    generated_by BIGINT NULL COMMENT 'User ID who triggered generation (null for automated)',
    file_path VARCHAR(500) NOT NULL COMMENT 'Path to the generated report file',
    file_format VARCHAR(10) NOT NULL COMMENT 'File format (pdf, xlsx, csv, docx)',
    file_size BIGINT NULL COMMENT 'File size in bytes',
    status ENUM('pending', 'completed', 'failed') DEFAULT 'pending' COMMENT 'Generation status',
    error_message TEXT NULL COMMENT 'Error details if generation failed',
    generation_time_seconds INT NULL COMMENT 'Time taken to generate report in seconds',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When generation was requested',
    completed_at TIMESTAMP NULL COMMENT 'When generation completed (or failed)',
    FOREIGN KEY (scheduled_report_id) REFERENCES scheduled_reports(id) ON DELETE SET NULL,
    FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_scheduled_report (scheduled_report_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_generated_by (generated_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report generation history log';

-- Table: report_templates
-- Stores custom report builder templates created by administrators
CREATE TABLE IF NOT EXISTS report_templates (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT 'Template name',
    description TEXT NULL COMMENT 'Template description',
    created_by BIGINT NOT NULL COMMENT 'User ID who created the template',
    template_config JSON NOT NULL COMMENT 'Template configuration (components, layout, settings)',
    is_public BOOLEAN DEFAULT FALSE COMMENT 'Whether template is visible to other admins',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When template was created',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_created_by (created_by),
    INDEX idx_is_public (is_public)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Custom report builder templates';

-- Table: report_cache
-- Caches query results for frequently generated reports to improve performance
CREATE TABLE IF NOT EXISTS report_cache (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cache_key VARCHAR(255) NOT NULL UNIQUE COMMENT 'Unique identifier for the cached result',
    cache_data LONGTEXT NOT NULL COMMENT 'Cached data (JSON serialized)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When cache entry was created',
    expires_at TIMESTAMP NOT NULL COMMENT 'When cache entry expires',
    hit_count INT DEFAULT 0 COMMENT 'Number of times this cache was accessed',
    INDEX idx_cache_key (cache_key),
    INDEX idx_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Query result cache for reports';

-- Add indexes for optimized report queries
-- These indexes improve performance for common report queries

-- Index for application status and study section queries
ALTER TABLE applications ADD INDEX idx_report_status_studysection (status, study_section_id, created_at);

-- Index for grant type and status queries
ALTER TABLE applications ADD INDEX idx_report_granttype_status (grant_type_id, status, updated_at);

-- Index for reviewer queries with completion status
ALTER TABLE reviews ADD INDEX idx_report_reviewer_completion (reviewer_id, is_final, created_at);

-- Index for application time-series queries
ALTER TABLE applications ADD INDEX idx_report_timeseries (created_at, status);

-- Insert default scheduled reports example (for documentation)
-- This is commented out as it should be created through the UI
-- INSERT INTO scheduled_reports (name, description, created_by, report_config, schedule_type, schedule_config)
-- VALUES (
--     'Weekly Application Summary',
--     'Weekly summary of all applications by status and study section',
--     1,
--     '{"filters": {"date_range": "last_7_days"}, "grouping": ["status", "study_section"], "format": "pdf"}',
--     'weekly',
--     '{"day_of_week": "monday", "time": "08:00", "timezone": "America/New_York"}'
-- );
